version: 2
project_name: cvtr

builds:
  - id: cvtr
    main: ./cmd
    binary: cvtr
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X 'main.ProgramVersion={{.Version}}'

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz

checksum:
  name_template: "checksums.txt"

brews:
  - repository:
      owner: chebread
      name: homebrew-cvtr
      branch: master
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/chebread/cvtr"
    description: "A dead simple currency tool for your terminal."
    license: "MIT"
    install: |
      bin.install "cvtr"
